/**
 * Style reminder: simple card system. Keep the page compact, friendly, and easy to scan.
 * Use the coastal palette, soft borders, small shadows, and no long editorial blocks.
 */
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BriefcaseBusiness, Github, Globe2, Instagram, Linkedin, Mail, Menu, Moon, Search, Send, Sun, X, Youtube } from "lucide-react";
import { toast } from "sonner";

const assetBase = import.meta.env.BASE_URL; const assets = { ai: `${assetBase}assets/project-ai.jpg`, brand: `${assetBase}assets/project-brand.jpg`, content: `${assetBase}assets/project-content.jpg`, mark: `${assetBase}assets/ke-mark.png` };
type Lang = "ar" | "en";
const text = {
  ar: { home:"الرئيسية", work:"أعمالي", about:"عني", tutorials:"شروحات", contact:"تواصل", hello:"أهلًا، أنا خيري عيد علي", role:"صانع محتوى ومصمم مهتم بالتقنية والذكاء الاصطناعي.", bio:"أحوّل الأفكار المعقدة إلى محتوى وتجارب رقمية بسيطة وواضحة.", view:"شاهد أعمالي", contactMe:"تواصل معي", selected:"أعمال مختارة", skills:"المهارات والخبرات", recent:"شروحات ومقالات", send:"إرسال الرسالة", name:"الاسم", email:"البريد الإلكتروني", message:"رسالتك", all:"الكل", placeholder:"ابحث في الأعمال", success:"تم إرسال رسالتك بنجاح.", soon:"هذه الميزة ستكون متاحة قريبًا." },
  en: { home:"Home", work:"Work", about:"About", tutorials:"Tutorials", contact:"Contact", hello:"Hi, I’m Khairy Eid Ali", role:"A content creator and designer interested in technology and AI.", bio:"I turn complex ideas into simple, clear digital content and experiences.", view:"View my work", contactMe:"Contact me", selected:"Selected work", skills:"Skills & experience", recent:"Tutorials & articles", send:"Send message", name:"Name", email:"Email", message:"Your message", all:"All", placeholder:"Search work", success:"Your message was sent successfully.", soon:"This feature is coming soon." },
};
const projects = [
  { title:"AI, in plain language", cat:"ai", typeAr:"ذكاء اصطناعي", typeEn:"AI", descAr:"محتوى يشرح أدوات الذكاء الاصطناعي بلغة عملية.", descEn:"Content that explains AI tools in practical language.", detailAr:"منظومة محتوى تساعد المبتدئين على فهم أدوات الذكاء الاصطناعي واستخدامها في العمل اليومي، من خلال خرائط محتوى وشروحات قصيرة.", detailEn:"A content system helping beginners understand and use AI tools in their daily work through content maps and short explainers.", toolsAr:"بحث · استراتيجية محتوى · كتابة", toolsEn:"Research · Content strategy · Writing", url:"", image:assets.ai },
  { title:"A softer brand system", cat:"design", typeAr:"تصميم", typeEn:"Design", descAr:"هوية بصرية لمشروع رقمي واضح وإنساني.", descEn:"A clear and human visual identity for a digital project.", detailAr:"نظام بصري متكامل لمشروع رقمي ناشئ، يوازن بين البساطة والدفء ويجعل الواجهة أسهل في الفهم وأكثر اتساقًا.", detailEn:"A visual system for an emerging digital project, balancing simplicity and warmth to make the interface clearer and more consistent.", toolsAr:"هوية بصرية · واجهات · نظام ألوان", toolsEn:"Identity · Interface · Color system", url:"", image:assets.brand },
  { title:"The content studio", cat:"content", typeAr:"محتوى", typeEn:"Content", descAr:"نظام بسيط لتخطيط المحتوى وإنتاجه.", descEn:"A simple system for planning and producing content.", detailAr:"طريقة عمل مرنة تبدأ من الفكرة وتنتهي بالنشر، مع قوالب تساعد على الحفاظ على جودة المحتوى واستمراريته.", detailEn:"A flexible workflow from idea to publishing, with templates that help maintain content quality and consistency.", toolsAr:"تحرير · تخطيط · سير عمل", toolsEn:"Editorial · Planning · Workflow", url:"", image:assets.content },
];

export default function Home() {
  const [lang,setLang] = useState<Lang>("ar"); const [dark,setDark] = useState(false); const [menu,setMenu] = useState(false); const [filter,setFilter] = useState("all"); const [search,setSearch] = useState(""); const [selectedProject,setSelectedProject] = useState<(typeof projects)[number] | null>(null); const t=text[lang]; const rtl=lang === "ar";
  const shown=useMemo(() => projects.filter(p => (filter === "all" || p.cat === filter) && `${p.title} ${p.descAr} ${p.descEn}`.toLowerCase().includes(search.toLowerCase())),[filter,search]); useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setSelectedProject(null); }; if (selectedProject) { document.body.style.overflow = "hidden"; window.addEventListener("keydown", closeOnEscape); } return () => { document.body.style.overflow = ""; window.removeEventListener("keydown", closeOnEscape); }; }, [selectedProject]);
  const go=(id:string) => { document.getElementById(id)?.scrollIntoView({behavior:"smooth"}); setMenu(false); };
  const submit=(e:React.FormEvent) => { e.preventDefault(); toast.success(t.success); };
  return <div className={dark ? "site dark-mode" : "site"} dir={rtl ? "rtl":"ltr"}>
    <header className="topbar"><div className="shell nav"><button className="brand" onClick={() => go("top")}><img src={assets.mark} alt="KE" /><span>Khairy Eid <b>Ali</b></span></button><div className={menu ? "links open":"links"}><button onClick={() => go("top")}>{t.home}</button><button onClick={() => go("work")}>{t.work}</button><button onClick={() => go("about")}>{t.about}</button><button onClick={() => go("tutorials")}>{t.tutorials}</button><button onClick={() => go("contact")}>{t.contact}</button></div><div className="nav-tools"><button onClick={() => setLang(lang === "ar" ? "en":"ar")} className="small-btn">{lang === "ar" ? "EN":"ع"}</button><button onClick={() => setDark(!dark)} className="small-btn" aria-label="theme">{dark ? <Sun size={16}/>:<Moon size={16}/>}</button><button onClick={() => setMenu(!menu)} className="small-btn menu-toggle" aria-label="menu">{menu ? <X size={17}/>:<Menu size={17}/>}</button></div></div></header>
    <main id="top" className="shell main">
      <section className="profile-card"><div className="profile-copy"><p className="label">{rtl ? "PORTFOLIO شخصي":"PERSONAL PORTFOLIO"}</p><h1>{t.hello}</h1><h2>{t.role}</h2><p>{t.bio}</p><div className="actions"><button className="button primary" onClick={() => go("work")}>{t.view}<ArrowUpRight size={16}/></button><button className="button ghost" onClick={() => go("contact")}>{t.contactMe}</button></div><div className="socials"><a href="https://www.linkedin.com" target="_blank" rel="noreferrer"><Linkedin size={16}/> LinkedIn</a><a href="https://www.instagram.com" target="_blank" rel="noreferrer"><Instagram size={16}/> Instagram</a><a href="https://github.com" target="_blank" rel="noreferrer"><Github size={16}/> GitHub</a></div></div><div className="profile-side"><div className="avatar"><img src={assets.mark} alt="Khairy Eid Ali"/></div><span className="available"><i/> {rtl ? "متاح للتعاون":"Available for work"}</span><div className="location"><Globe2 size={16}/> Cairo · Remote</div></div></section>
      <section id="work" className="section-block"><div className="section-top"><div><span className="number">01</span><h2>{t.selected}</h2></div><div className="tools"><div className="filters"><button className={filter === "all" ? "active":""} onClick={() => setFilter("all")}>{t.all}</button><button className={filter === "ai" ? "active":""} onClick={() => setFilter("ai")}>AI</button><button className={filter === "design" ? "active":""} onClick={() => setFilter("design")}>{rtl ? "تصميم":"Design"}</button><button className={filter === "content" ? "active":""} onClick={() => setFilter("content")}>{rtl ? "محتوى":"Content"}</button></div><label className="search"><Search size={15}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder={t.placeholder}/></label></div></div><div className="card-grid">{shown.map(p => <article className="work-card" key={p.title} onClick={() => setSelectedProject(p)} tabIndex={0} role="button" onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelectedProject(p); } }}><img src={p.image} alt={p.title} loading="lazy"/><div className="card-body"><span className="tag">{rtl ? p.typeAr:p.typeEn}</span><h3>{p.title}</h3><p>{rtl ? p.descAr:p.descEn}</p><button className="card-link" onClick={event => { event.stopPropagation(); setSelectedProject(p); }}>{rtl ? "عرض التفاصيل":"View details"}<ArrowUpRight size={15}/></button></div></article>)}</div></section>
      <section id="about" className="two-cards"><article className="info-card blue-card"><span className="number">02</span><h2>{t.skills}</h2><div className="chips"><span>Content strategy</span><span>AI & tools</span><span>UI design</span><span>Technical writing</span><span>Brand identity</span><span>Digital projects</span></div></article><article className="info-card yellow-card"><BriefcaseBusiness size={24}/><h3>{rtl ? "طريقة عملي":"How I work"}</h3><p>{rtl ? "أبدأ بفهم الفكرة، ثم أرتبها وأحوّلها إلى تجربة سهلة الاستخدام." : "I start by understanding the idea, then shape it into an easy-to-use experience."}</p><button className="card-link" onClick={() => go("contact")}>{t.contactMe}<ArrowUpRight size={15}/></button></article></section>
      <section id="tutorials" className="section-block compact"><div className="section-top"><div><span className="number">03</span><h2>{t.recent}</h2></div><button className="card-link" onClick={() => toast.info(t.soon)}>{rtl ? "عرض الكل":"See all"}<ArrowUpRight size={15}/></button></div><div className="list-card"><button onClick={() => toast.info(t.soon)}><span>01</span><strong>{rtl ? "كيف تبدأ نظامًا عمليًا لصناعة المحتوى؟":"How to build a practical content system"}</strong><small>8 min read <ArrowUpRight size={14}/></small></button><button onClick={() => toast.info(t.soon)}><span>02</span><strong>{rtl ? "دليل مبسط لفهم أدوات الذكاء الاصطناعي":"A simple guide to understanding AI tools"}</strong><small>12 min read <ArrowUpRight size={14}/></small></button><button onClick={() => toast.info(t.soon)}><span>03</span><strong>{rtl ? "لماذا تحتاج المشاريع إلى لغة بصرية؟":"Why projects need a visual language"}</strong><small>6 min read <ArrowUpRight size={14}/></small></button></div></section>
      <section id="contact" className="contact-card"><div><span className="number">04</span><h2>{rtl ? "خلينا نتكلم عن فكرتك":"Let’s talk about your idea"}</h2><p>{rtl ? "رسالة قصيرة تكفي لبدء الحوار.":"A short message is enough to start a conversation."}</p><a href="mailto:hello@khairyali.com"><Mail size={16}/> hello@khairyali.com</a></div><form onSubmit={submit}><input required placeholder={t.name}/><input required type="email" placeholder={t.email}/><textarea required rows={3} placeholder={t.message}/><button className="button primary" type="submit">{t.send}<Send size={15}/></button></form></section>
    </main>{selectedProject && <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setSelectedProject(null); }}><div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title"><button className="modal-close" onClick={() => setSelectedProject(null)} aria-label={rtl ? "إغلاق":"Close"}><X size={18}/></button><img src={selectedProject.image} alt=""/><div className="modal-content"><span className="tag">{rtl ? selectedProject.typeAr:selectedProject.typeEn}</span><h2 id="project-modal-title">{selectedProject.title}</h2><p>{rtl ? selectedProject.detailAr:selectedProject.detailEn}</p><div className="modal-meta"><strong>{rtl ? "الأدوات المستخدمة":"Tools used"}</strong><span>{rtl ? selectedProject.toolsAr:selectedProject.toolsEn}</span></div>{selectedProject.url ? <a className="button primary" href={selectedProject.url} target="_blank" rel="noreferrer">{rtl ? "زيارة المشروع":"Visit project"}<ArrowUpRight size={15}/></a> : <button className="button primary" disabled title={rtl ? "لم تتم إضافة رابط بعد":"No project URL has been added yet"}>{rtl ? "الرابط غير متاح":"Link unavailable"}<ArrowUpRight size={15}/></button>}</div></div></div>}<footer className="footer"><div className="shell"><span>© 2024 Khairy Eid Ali</span><span>{rtl ? "بسيط وواضح":"Simple and clear"}</span></div></footer>
  </div>;
}
